"""add feild in restaurant table

Revision ID: 03c703089f0f
Revises: 0d328d686373
Create Date: 2024-07-08 14:52:07.800986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03c703089f0f'
down_revision: Union[str, None] = '0d328d686373'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant', sa.Column('cuisine_type', sa.String(length=50), nullable=False))
    op.add_column('restaurant', sa.Column('opening_hours', sa.String(length=100), nullable=False))
    op.add_column('restaurant', sa.Column('average_cost', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurant', 'average_cost')
    op.drop_column('restaurant', 'opening_hours')
    op.drop_column('restaurant', 'cuisine_type')
    # ### end Alembic commands ###
